name: Docker

on:
  workflow_dispatch:
  schedule:
  - cron: '22 5 22 * *'
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - id: string 
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          context: ./worker
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}/mapgen-worker:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.string.outputs.lowercase }}/mapgen-worker:latest
          cache-to: type=inline
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          context: ./frontend
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}/mapgen-frontend:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.string.outputs.lowercase }}/mapgen-frontend:latest
          cache-to: type=inline
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
